In [43]:
# this is unrelated to the class .. It just helps displaying all outputs in a cell instead of just last one
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# NumPy Basics: Arrays and Much More

NumPy, short for Numerical Python, is one of the most important foundational pack‐ ages for numerical computing in Python
<br>
Here are some of the things you’ll find in NumPy:
- ndarray, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities
- Mathematical functions for fast operations on entire arrays of data without having to write loops.
- Tools for reading/writing array data to disk and working with memory-mapped files.
- Linear algebra, random number generation, and Fourier transform capabilities.


You can import using import numpy. It is most common to see import numpy as np, this will import an instance and you can now call numpy as a shorter name which is np, this name "np" can be changed to anything you want but it became common practice to use np. Dealing with a numpy array is very similar to dealing with a python list except you now have many cool extra features and helping function

In [36]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
print(my_arr[:10])
print(my_list[:10])

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Using non loop operation in Numpy is a lot faster than using list comprehension

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 14.5 ms, sys: 4.51 ms, total: 19 ms
Wall time: 16.9 ms
CPU times: user 667 ms, sys: 207 ms, total: 874 ms
Wall time: 875 ms


## The NumPy ndarray: A Multidimensional Array Object

You can use Numpy to create and process multi dimension array (2d, 3d, ... etc). Numpy supports simple and complex matrix operations.

### Creating ndarrays

In [2]:
import numpy as np
np.random.seed(1234)  #  Fixes the seed of the random genrator to guarantee same results every run
data = np.random.randn(2, 3) # Generate a random 2X3 array
data

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294]])

You can also convert from lists to ndarray using numpy

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

You can check the number of dimensions of an array using ndim and you can check the shape (number of cols and rows) using shape. dtype tells you the type of the array

In [6]:
print(arr1.dtype)
print(arr2.ndim) 
arr2.shape

float64
2


(2, 4)

Create an array of zeros

In [8]:
np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))

array([[[1.42137879e-076, 1.76540643e+137],
        [9.02193423e+217, 6.01347002e-154],
        [2.95160906e-075, 4.11017660e+223]],

       [[9.45956265e-076, 6.98191945e+252],
        [2.14392305e+137, 9.02193423e+217],
        [9.45956265e-076, 2.95153379e-075]]])

create an array of ones

In [9]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

You can also use arange, similar to range in lists

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

Changing the type of elements of a numpy array can happen at creation such as:

In [11]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

float64


dtype('int32')

It can also happen after creation using astype

In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
float_arr.dtype


int64


dtype('float64')

In [15]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Element Wise Operations with NumPy Arrays

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr*10
arr+arr
arr - arr
arr * arr
1 / arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

You can also do logical operations

In [30]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### You can also do universal functions and fast element-wise array functions

In [41]:
np.sqrt(arr)
np.exp(arr)
np.sin(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

There is also special helping fuctions such as `np.maximum(x,y)`, it returns a value of the highest element in an element wise comparison between two arrays

In [37]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y)

array([-2.0749776 ,  0.2477922 , -0.89715678, -0.13679483,  0.01828919,
        0.75541398,  0.21526858,  0.84100879])

array([-1.44581008, -1.40197328, -0.1009182 , -0.54824245, -0.14461951,
        0.35402033, -0.03551303,  0.56573831])

array([-1.44581008,  0.2477922 , -0.1009182 , -0.13679483,  0.01828919,
        0.75541398,  0.21526858,  0.84100879])

In [34]:
arr = np.random.randn(7) * 5
print(arr)
remainder, whole_part = np.modf(arr)
print(whole_part)
print(remainder)

[-1.01323162 -3.27984672  0.96710688  2.76719455  6.59075777 -2.34652642
  3.37777043]
[-1. -3.  0.  2.  6. -2.  3.]
[-0.01323162 -0.27984672  0.96710688  0.76719455  0.59075777 -0.34652642
  0.37777043]


### Basic Indexing and Slicing

You can slice a numpy array similar to how you slice a list

In [42]:
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[5:8] = 12
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5

array([5, 6, 7])

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Slicing an array does not result in a separate array but it results in an object that relates back to the original array. Changes in that object result in changes in the original numpy array. This is not the same as the list

In [50]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    64, 12345,    64,     8,
           9])

In [51]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Just like a list slicing 2D array with one index will result in the entire row

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

You can now pick one specific element from the 2D array using double indexing in two ways

In [29]:
arr2d[0][2]
arr2d[0, 2]

3

Even MORE DIMENSIONS .. 3D .. confusing?

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr3d[1, 0]

array([7, 8, 9])

In [36]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

#### More on 2D indexing

In [60]:
print(arr2d)
arr2d[:2] # Give me all row up until row 2, row 2 is not included

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2d[:2, 1:]  # give me all rows up until row 2 and all columns starting from column 1

array([[2, 3],
       [5, 6]])

In [59]:
arr2d[:, :1]  # give me all rows and all columns up until col 1

array([[1],
       [4],
       [7]])

### Boolean Indexing

In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [47]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [48]:
data[names == 'Bob']

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.669 , -0.4386, -0.5397,  0.477 ]])

In [49]:
data[names == 'Bob', 2:]
data[names == 'Bob', 3]

array([1.2464, 0.477 ])

In [50]:
names != 'Bob'
data[~(names == 'Bob')]

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [51]:
cond = names == 'Bob'
data[~cond]

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [52]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241]])

In [53]:
data[data < 0] = 0
data

array([[0.0929, 0.2817, 0.769 , 1.2464],
       [1.0072, 0.    , 0.275 , 0.2289],
       [1.3529, 0.8864, 0.    , 0.    ],
       [1.669 , 0.    , 0.    , 0.477 ],
       [3.2489, 0.    , 0.    , 0.1241],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

In [54]:
data[names != 'Joe'] = 7
data

array([[7.    , 7.    , 7.    , 7.    ],
       [1.0072, 0.    , 0.275 , 0.2289],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [7.    , 7.    , 7.    , 7.    ],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

## Conclusion