In [1]:
# this is unrelated to the class .. It just helps displaying all outputs in a cell instead of just last one
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Universal Functions: Fast Element-Wise Array Functions

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr*10
arr+arr
arr - arr
arr * arr
1 / arr
arr ** 0.5
2**arr

array([[10., 20., 30.],
       [40., 50., 60.]])

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

array([[ 2.,  4.,  8.],
       [16., 32., 64.]])

You can also do logical operations

In [30]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

You can also do some complex functions per elements

In [18]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)
np.sin(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y) # forms a new array which is the elements wise max of two arrays

array([-0.65182362, -1.27177472,  1.0945961 , -0.1048369 ,  1.4227916 ,
       -0.95835737,  0.11794153,  0.60895135])

array([-1.04486071, -0.98673983,  1.13297829, -1.08143701, -0.69010923,
       -0.66156635, -0.83123579, -0.89916941])

array([-0.65182362, -0.98673983,  1.13297829, -0.1048369 ,  1.4227916 ,
       -0.66156635,  0.11794153,  0.60895135])

In [20]:
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr)  # devide the numbers in an array to float and integer
remainder
whole_part

array([ 2.89675791,  4.94209589,  1.51503878, -5.54167591, -7.70845778,
       -9.11572969, -6.66227504])

array([ 0.89675791,  0.94209589,  0.51503878, -0.54167591, -0.70845778,
       -0.11572969, -0.66227504])

array([ 2.,  4.,  1., -5., -7., -9., -6.])

## More on Indexing
There are more ways to index an array and get specific elements or combination of rows and columns

In [3]:
import numpy as np
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [4]:
# get rows with indices of 4,3,0 and 6
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [5]:
# now get rows from the end
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [6]:
# This format will get you multiple elements with one line .. the length of rows and columns indices has to be the same
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

array([ 4, 23, 29, 10])

In [7]:
# this format will get you multiple rows and columns with one command .. think about doing it on two steps.
# Length of rows and cols indices does not have to be the same
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Logical (Boolean) Indexing

This is a way to access or index a numpy array based on conditions. These conditions can be on elements from different array or of the same array. Imagine the following. You have an excel sheet of the employee sales where each row is based on the employee name and columns are the sales in each time period. Somehow, we magically where able to read this excel sheet into two numpy array. The first is Names which has the employee names and the second is data. Data number of rows is the same as the length of the array Names. The number of columns is based on the number of time periods (for example, Q1, Q2, Q3 and Q4 sales).

In [8]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

array([[-0.00882227,  3.47958728,  0.18840519,  1.33801577],
       [-1.43638895, -1.51707805, -1.51046262,  0.2113159 ],
       [ 0.68055119,  0.66625714,  0.8169562 ,  0.06508953],
       [-0.46885228, -1.54629395, -0.25294876, -0.54980315],
       [-0.97550479,  3.63976656,  0.65137687,  0.40244463],
       [ 0.65539078, -1.45249854,  0.70557028, -1.59272957],
       [ 0.41209238, -0.63019357, -0.14044931,  0.73394536]])

In [9]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

To get all the sales that Bob has done

In [10]:
data[names == 'Bob']

array([[-0.00882227,  3.47958728,  0.18840519,  1.33801577],
       [-0.46885228, -1.54629395, -0.25294876, -0.54980315]])

You can now do all sort of things with Bob's data. Such as finding the mean and the variance accross different axis

In [15]:
np.mean(data[names == 'Bob'])
np.mean(data[names == 'Bob'], axis=0)
np.mean(data[names == 'Bob'], axis=1)

0.2724109788062713

array([-0.23883728,  0.96664666, -0.03227178,  0.39410631])

array([ 1.24929649, -0.70447453])

You can also partition Bob's data

In [11]:
data[names == 'Bob', 2:] # bobs sales for Q3 and Q4
data[names == 'Bob', 3]  # bobs sales for Q4

array([[ 0.18840519,  1.33801577],
       [-0.25294876, -0.54980315]])

array([ 1.33801577, -0.54980315])

Now I want to check the sales of everybody else but Bob

In [12]:
names != 'Bob'
data[~(names == 'Bob')]

array([False,  True,  True, False,  True,  True,  True])

array([[-1.43638895, -1.51707805, -1.51046262,  0.2113159 ],
       [ 0.68055119,  0.66625714,  0.8169562 ,  0.06508953],
       [-0.97550479,  3.63976656,  0.65137687,  0.40244463],
       [ 0.65539078, -1.45249854,  0.70557028, -1.59272957],
       [ 0.41209238, -0.63019357, -0.14044931,  0.73394536]])

In [13]:
cond = names == 'Bob'
data[~cond]

array([[-1.43638895, -1.51707805, -1.51046262,  0.2113159 ],
       [ 0.68055119,  0.66625714,  0.8169562 ,  0.06508953],
       [-0.97550479,  3.63976656,  0.65137687,  0.40244463],
       [ 0.65539078, -1.45249854,  0.70557028, -1.59272957],
       [ 0.41209238, -0.63019357, -0.14044931,  0.73394536]])

You can also use and/or in a condition .. The following gets bob's and will's data

In [14]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([ True, False,  True,  True,  True, False, False])

array([[-0.00882227,  3.47958728,  0.18840519,  1.33801577],
       [ 0.68055119,  0.66625714,  0.8169562 ,  0.06508953],
       [-0.46885228, -1.54629395, -0.25294876, -0.54980315],
       [-0.97550479,  3.63976656,  0.65137687,  0.40244463]])

Conditions do not have to be based on names only. It can be used to manipulate the data itself

In [16]:
data[data < 0] = 0
data

array([[0.        , 3.47958728, 0.18840519, 1.33801577],
       [0.        , 0.        , 0.        , 0.2113159 ],
       [0.68055119, 0.66625714, 0.8169562 , 0.06508953],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 3.63976656, 0.65137687, 0.40244463],
       [0.65539078, 0.        , 0.70557028, 0.        ],
       [0.41209238, 0.        , 0.        , 0.73394536]])

In [17]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.2113159 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.65539078, 0.        , 0.70557028, 0.        ],
       [0.41209238, 0.        , 0.        , 0.73394536]])

# Some Array Operations

We have seen some element wise operations such as multiplication, addition, elements division. How about some matrices operations. Things that we studied before in Linear Algebra. Such as, matrix multiplcation, inverse, transpose, determinants. 

To transpose an array

In [21]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

To multiply two matrices

In [22]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)
np.dot(x, y) # same thing

array([[1., 2., 3.],
       [4., 5., 6.]])

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

array([[ 28.,  64.],
       [ 67., 181.]])

array([[ 28.,  64.],
       [ 67., 181.]])

The package `linalg` is the linear algebra package in numpy and it contains many useful functions related to linear algebra

In [24]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)   # to invert a matrix
mat.dot(inv(mat)) # matrix multiplied by its inverse will give you the unity matrix
q, r = qr(mat) # Factor the matrix a as qr, where q is orthonormal and r is upper-triangular.
q
r

array([[ 6.47967919,  1.74308007, -1.27164973, -8.30814113,  3.45811357],
       [ 1.74308007,  5.81895129, -0.93622527, -5.56063076,  8.17215281],
       [-1.27164973, -0.93622527,  0.49691672,  2.08277306, -1.17651736],
       [-8.30814113, -5.56063076,  2.08277306, 13.10568892, -9.08883863],
       [ 3.45811357,  8.17215281, -1.17651736, -9.08883863, 13.43665329]])

array([[ 1.00000000e+00,  9.39388898e-16, -4.45026976e-17,
         6.38829844e-15,  7.70601058e-17],
       [ 1.21274734e-15,  1.00000000e+00,  3.74424763e-16,
         4.80863961e-15,  1.25836149e-15],
       [-1.69082769e-15, -2.92632112e-15,  1.00000000e+00,
         7.53619526e-16,  1.04193833e-15],
       [ 9.34356130e-16,  6.68733731e-16,  5.75422031e-16,
         1.00000000e+00, -4.11962241e-15],
       [-5.89554116e-17,  1.90165081e-15, -2.57619056e-16,
        -1.23511285e-15,  1.00000000e+00]])

array([[-0.68377024, -0.11418467, -0.2815051 ,  0.63666209,  0.18664511],
       [-0.24992062, -0.59241675,  0.57397026, -0.25018357,  0.44107641],
       [ 0.24902801, -0.71663863, -0.63642797, -0.12385989, -0.06350029],
       [-0.63383665,  0.03180205, -0.12107531, -0.58475505, -0.49055279],
       [-0.07895631,  0.34845653, -0.41426228, -0.41807874,  0.72521782]])

array([[-5.2643935 , -1.37581424,  5.04128767, -5.55397063, -1.129649  ],
       [ 0.        , -3.28362544, -9.24085516,  1.73219799,  2.38559306],
       [ 0.        ,  0.        , -3.83984895,  0.65256341,  0.07435872],
       [ 0.        ,  0.        ,  0.        , -0.12468766, -0.11545619],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.0539731 ]])

### Unique and Other Set Logic and More ...

In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

array([1, 2, 3, 4])

In [26]:
sorted(set(names))  # same thing without numpy

['Bob', 'Joe', 'Will']

`np.in1d` Find if an array has some or all of its elements in another array or not

In [27]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

To find out where are the indices of an element that satisfies certain conditions in an array use `np.where`

In [29]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr>0)

array([[-0.03317005,  0.90375865,  2.2266901 ,  0.0235131 ],
       [ 0.24598961, -0.50955829,  0.87533881,  2.55062675],
       [-0.08483985,  2.02938723,  1.05344969,  0.8906276 ],
       [-0.44903748,  2.49187206,  0.63076208,  3.0117794 ]])

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([1, 2, 3, 0, 2, 3, 1, 2, 3, 1, 2, 3]))

In [30]:
np.where(arr > 0, 2, -2) # make a new arrays set corresponding positive elements of arr by 2 and negative elements to -2
np.where(arr > 0, 2, arr) # make a new arrays set corresponding positive elements of arr by 2 and leave everything else the same

array([[-2,  2,  2,  2],
       [ 2, -2,  2,  2],
       [-2,  2,  2,  2],
       [-2,  2,  2,  2]])

array([[-0.03317005,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.50955829,  2.        ,  2.        ],
       [-0.08483985,  2.        ,  2.        ,  2.        ],
       [-0.44903748,  2.        ,  2.        ,  2.        ]])

To sum only the positive elements in an array, you can do one of the following methods

In [31]:
arr = np.random.randn(100)
sum(arr[arr>0])
(arr[arr>0]).sum()

49.15579766437154

49.15579766437154

In [33]:
# To find the numnber of positive elements in an array, you can use one of the following methods
len(arr[arr>0])
(arr>0).sum()

63

63

You can do all other sort of cool things such as finding cummulative sum or cummulative products. 

In [34]:
arr=np.arange(5)
arr
arr.cumsum()

array([0, 1, 2, 3, 4])

array([ 0,  1,  3,  6, 10])

# Conclusion

Numpy is a cool library due to its extensive, fast and various operations that can save time in both writing and processing a code. There is still a lot more in Numpy. From now on, `Google` and `Stackoverflow` are your friends. Google what is on your mind and add the words python to it and most of the time you will find your answer in the first search results. Numpy is a very extensive library and you get to uncover more and more by practice. For now, what we had is enough to get you going and start digging deeper in data science. See you next week